import { Project, SyntaxKind, Node } from "ts-morph";
import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";

const program = new Command();

program
  .name("fac-cli")
  .description("Farcaster Agent Compiler - Generate agent.json from your Mini App")
  .version("1.0.0")
  .option("-i, --input <path>", "Input directory (Next.js project root)", ".")
  .option("-o, --output <path>", "Output file path", "./public/.farcaster/agent.json")
  .action(async (options: { input: string, output: string }) => {
    const projectRoot = path.resolve(options.input);
    const outputPath = path.resolve(options.output);

    console.log(`🚀 Scanning project at: ${projectRoot}`);

    const project = new Project({
      tsConfigFilePath: path.join(projectRoot, "tsconfig.json"),
      skipAddingFilesFromTsConfig: true,
    });

    const actions = [];

    // 1. Scan API Routes (pages/api)
    const apiPath = path.join(projectRoot, "pages", "api");
    if (fs.existsSync(apiPath)) {
      const apiFiles = fs.readdirSync(apiPath).filter(f => f.endsWith(".ts") || f.endsWith(".js"));
      for (const file of apiFiles) {
        const sourceFile = project.addSourceFileAtPath(path.join(apiPath, file));
        const action = extractApiAction(sourceFile, file);
        if (action) actions.push(action);
      }
    }

    // 2. Scan Components for Transactions (Components/Hooks)
    const componentsPath = path.join(projectRoot, "components");
    if (fs.existsSync(componentsPath)) {
      const componentFiles = fs.readdirSync(componentsPath).filter(f => f.endsWith(".tsx") || f.endsWith(".jsx"));
      for (const file of componentFiles) {
        const sourceFile = project.addSourceFileAtPath(path.join(componentsPath, file));
        const txActions = extractTransactionActions(sourceFile);
        actions.push(...txActions);
      }
    }

    const manifest: any = {
      version: "1.0",
      name: "Generated App",
      description: "Auto-generated by Farcaster Agent Compiler",
      actions,
    };

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, JSON.stringify(manifest, null, 2));
    console.log(`✅ Agent manifest generated at: ${outputPath}`);
  });

function extractApiAction(sourceFile: any, fileName: string) {
  const name = fileName.replace(/\.[jt]s$/, "");
  const action: any = {
    id: name,
    name: name.charAt(0).toUpperCase() + name.slice(1),
    description: `API action for ${name}`,
    type: "api",
    endpoint: `/api/${name}`,
    method: "POST", // Defaulting to POST for actions
    parameters: {} as Record<string, any>,
  };

  // Look for Zod schemas
  const variableDeclarations = sourceFile.getVariableDeclarations();
  for (const decl of variableDeclarations) {
    const initializer = decl.getInitializer();
    if (initializer && initializer.getText().includes("z.object")) {
       // Simplistic extraction of Zod schema keys for PoC
       const text = initializer.getText();
       const matches = text.matchAll(/(\w+):\s*z\./g);
       for (const match of matches) {
         action.parameters[match[1]] = { type: "unknown" };
       }
    }
  }

  return action;
}

function extractTransactionActions(sourceFile: any) {
  const actions: any[] = [];
  
  // Look for writeContract calls
  sourceFile.forEachDescendant((node: Node) => {
    if (Node.isCallExpression(node)) {
      const expression = node.getExpression();
      if (expression.getText().includes("writeContract")) {
        const args = node.getArguments();
        if (args.length > 0 && Node.isObjectLiteralExpression(args[0])) {
          const props = args[0].getProperties();
          const functionNameProp = props.find(p => p.getText().includes("functionName"));
          
          if (functionNameProp) {
            const funcName = functionNameProp.getText().split(":")[1].trim().replace(/['"]/g, "");
            actions.push({
              id: `tx-${funcName}`,
              name: funcName.charAt(0).toUpperCase() + funcName.slice(1),
              description: `Onchain transaction: ${funcName}`,
              type: "contract",
              contract: {
                address: "extracted-at-runtime",
                function: funcName,
              }
            });
          }
        }
      }
    }
  });

  return actions;
}

program.parse();
